# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKSi-S3gIFup3gdTI1Bk7pMrBW2lYtSb
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

# Load the model, vectorizer, and PCA coordinates
kmeans = joblib.load("kmeans_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")
pca_df = pd.read_csv("pca_coordinates.csv")

# Page title
st.title("Tweet Text Clustering App")
st.write("This app clusters tweets using TF-IDF vectorization, KMeans clustering, and PCA for visualization.")

# Sidebar
st.sidebar.header("Enter a tweet to see its cluster")

# User input
user_input = st.sidebar.text_area("Tweet text", "Type your tweet here...")

if user_input:
    cleaned_input = user_input.lower()
    cleaned_input = ''.join([char for char in cleaned_input if char.isalpha() or char.isspace()])
    cleaned_input = ' '.join([word for word in cleaned_input.split() if len(word) > 2])

    # Vectorize and predict cluster
    vec_input = vectorizer.transform([cleaned_input])
    cluster_pred = kmeans.predict(vec_input)[0]

    st.sidebar.success(f"Predicted Cluster: {cluster_pred}")

# Display PCA plot
st.subheader("2D Visualization of Tweet Clusters")
plt.figure(figsize=(8, 6))
sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='cluster', palette='viridis', legend='full')
plt.title("Tweet Clusters by PCA")
st.pyplot(plt)